name: continuous integration example

on:
  push:
    branches:
      main

jobs:
   build-and-test:
      runs-on: self-hosted

      steps:
         - uses: actions/checkout@v1

         - name: Install Java
           uses: actions/setup-java@v1
           with:
             java-version: "11"

         - name: Build with gradle
           working-directory: .
           run: |
             chmod +x gradlew
             ./gradlew build -x test

         - name: Run tests
           working-directory: .
           run: |
             chmod +x gradlew
             ./gradlew test

   deploy:
     needs: build-and-test
     runs-on: self-hosted
     steps:
       - uses: actions/checkout@v1
       - name: Copy repo to cloud
         uses: appleboy/scp-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           port: ${{ secrets.PORT }}
           key: ${{ secrets.KEY }}
           source: "./"
           target: "~/prod"
       - name: Restart all instances on cloud
         uses: appleboy/ssh-action@master
         with: 
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           port: ${{ secrets.PORT }}
           key: ${{ secrets.KEY }}
           script: |
             cd ~/prod
             docker-compose down && docker-compose up --build -d
     
